### ISSUE TITLE
Return `?` instead of `#` on Provider OAuth Callbacks

### ISSUE THREAD

**Issue by acupofjose** [supabase/gotrue#1011]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am writing an application that works server side to receive OAuth callbacks. When following a `redirect_to` after OAuth completes, the information is put into the URL after a `#` instead of as a query string. However, since this is a server side application that has no access to the browser and [**URL content after a hash is not posted to the server**](https://stackoverflow.com/a/20901206/3629438), I am unable to parse the OAuth tokens in my application.

## To Reproduce

1. Auth User with Provider (Github)
2. Set RedirectTo to be `http://127.0.0.1:31419`
3. Check returned url in browser.

Returns a url like so:
```bash
http://127.0.0.1:31419/oauth/callback#access_token=ACCESS_TOKEN&expires_in=3600&provider_refresh_token=PROVIDER_REFRESH_TOKEN&provider_token=PROVIDER_TOKEN&refresh_token=REFRESH_TOKEN&token_type=bearer
```

## Expected behavior

```bash
http://127.0.0.1:31419/oauth/callback?access_token=ACCESS_TOKEN&expires_in=3600&provider_refresh_token=PROVIDER_REFRESH_TOKEN&provider_token=PROVIDER_TOKEN&refresh_token=REFRESH_TOKEN&token_type=bearer
```

## System information

- OS: Windows / Mac
- Browser: Chrome
- Language: C#

**Comment by acupofjose** [comment]
This is similar to #992, but asking to return on all requests instead of just errors.

**Comment by J0** [comment]
Hey @acupofjose,

Thanks for the request! This was actually intended as a security feature since  `?` params can be read by the server (and thus be logged together with access token) whereas `#` params remain in the browser. We are releasing another OAuth flow, [the PKCE Flow](https://github.com/supabase/gotrue/pull/891) which aims to allow users signing in with OAuth to receive  params with `?` prefixed.

The change should reach production in a week or two. We will follow up with the rest of the flows soon

Jo

**Comment by J0** [comment]
Going to close for now but let me know if there are further concerns.

Thanks!

**Comment by acupofjose** [comment]
Alright! I’ll get to implementing it on the c# clients. Thanks @J0!
