### ISSUE TITLE
signInWithOtp "Database error finding user" for new user with create_user: true

### ISSUE THREAD

**Issue by user72356** [supabase/gotrue#1106]
I'm using supabase.auth.signInWithOtp() to sign in/create a user (using email). With a brand-new database and the user NOT present in the database, I sometimes (it's intermittent) get the following error (this is a copy and paste from the request/response in browser:

Request:
```json
{"email":"user@example.com","data":{},"create_user":true,"gotrue_meta_security":{},"code_challenge":null,"code_challenge_method":null}
```

Response:
```json
{
    "code": 500,
    "msg": "Database error finding user",
    "error_id": "d8899365-2eea-46ce-a1ec-561724b7e743"
}
```

Is I hit my GUI button one more time to trigger signInWithOtp() again, it works, the user gets created in the DB and everything is dandy.

Please note that this is using a local development Supabase environment as provided by supabase-cli. 

I have not been able to test on my remote servers yet.

I'm not sure where to start troubleshooting this. I think gotrue runs in the Kong container. The logs tab for Kong in Docker Desktop has nothing worthwhile, just the HTTP log.

**Comment by kangmingtay** [comment]
Hi @user72356, can you please contact our support at https://app.supabase.com/support/new and reference this PR so that our support team knows that I asked you to contact us? We'll need to dig into your project to figure out the root cause. Alternatively, you can also take a look at your [project's auth logs](https://app.supabase.com/project/_/logs/explorer) to observe the underlying error

**Comment by kangmingtay** [comment]
closing this issue since we haven't heard back but feel free to reopen it or email us at support if you are still facing issues
