### ISSUE TITLE
`signInWithOtp()` not working with Twillio if we provide an `Service Sid` instead of phone number.

### ISSUE THREAD

**Issue by hasanmhallak** [supabase/gotrue#1186]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

It appears that providing a `Twilio Message Service Sid` instead of a phone number as shown in the docs [here](https://supabase.com/docs/guides/auth/phone-login/twilio#steps) will throw an exception from twillio itself. but I think the problem is from gotrue side not Twillio duo to the fact that it working normally when try it using `cURL` like this:
```bash
curl 'https://verify.twilio.com/v2/Services/[Service Sid]/Verifications' -X POST \
--data-urlencode 'To=+XXXXXXXXX' \
--data-urlencode 'Channel=sms' \
-u [Account Sid]:[Auth Token]
```

## Error
```bash
AuthException(message: Error sending confirmation sms: The 'From' number [Service Sid] is not a valid phone number, shortcode, or alphanumeric sender ID. More information: https://www.twilio.com/docs/errors/21212, statusCode: 400)
```

**Comment by azlekov** [comment]
Same issue here. +1

**Comment by hasanmhallak** [comment]
hey @J0, I'me sure what you meant by *hoping to use Twilio Verify with Supabase auth* but I tried this link to try and check if the `Twilio Message Service Sid` will work or not as Twillio docs said. And it works fine.

Given the exception I had, I can bet that supabase implementation uses the `SID` in the `From` field. Because when putting a number purchased from Twillio like the video in the docs it works fine.  


Purchasing a number from twillio will cost a monthly fee to preserve that number, and in this case using the `Service Sid` is more convenient.

**Comment by azlekov** [comment]
The SID can be checked if is a messaging or service ID. Based on that different APIs should be used.

References:
- https://github.com/nhost/hasura-auth/blob/main/src/routes/signin/passwordless/sms/sms.ts#L103-L127
- https://github.com/nhost/hasura-auth/blob/main/src/utils/twilio.ts#L5

**Comment by J0** [comment]
Hey @hasanmhallak,

Apologies, I re-read the message and realized that it could be potentially be interpreted as curt and even offensive. That was not my intention and I apologize if it came across that way. 

For context, we have a similar but separate provider, Twilio Verify, which is currently feature flagged and due to go out shortly. To make use of Twilio Verify we'd need to enable a flag on the project to allow the use of the feature. The flag would toggle `signInWithOtp` to use a separate API endpoint specific to Verify SIDs.  We'd previously release and retracted the documentation so wanted to check if y'all were part of the set of users who had seen the documentation and were trying to use the feature. I could have explained myself better - sorry about that.

Let me confirm that the endpoint is working with a Message Service ID and I'll see if we're ready to unflag the Twilio Verify endpoint shortly after.

**Comment by J0** [comment]
Hey all,

Thanks for your patience. Going to close this issue since we've since rolled out Twilio Verify and it should be possible to use the Twilio Verify provider with a Verification Service ID now. Do let us know if there are any further issues using Twilio with a Message Service ID or Twilio Verify with a Verification Service ID and we'll re-open issue.

Thanks everyone!
