### ISSUE TITLE
auth.users: add UNIQUE constraint to emails

### ISSUE THREAD

**Issue by imageck** [supabase/gotrue#1257]
This will allow to reference `auth.users` based on `email`, for example to record the author of a post, a comment or an article.

**Comment by sweatybridge** [comment]
Moving this issue to gotrue repo as the `auth` schema is entirely managed by gotrue.

**Comment by kangmingtay** [comment]
@imageck we won't be adding this because the `email` column is not necessarily unique. For example, currently, we allow a SAML SSO user and a normal user to have 2 different accounts with the same email. If we add a unique constraint to the email column, it doesn't allow for that use case.

In the future, we're also planning to update the oauth logins such that it does not rely on unique emails. 

If you need to reference a user based on email, it would be better if you include a foreign key constraint on the `auth.users.id` column and retrieve the email of the user using a join.
