### ISSUE TITLE
Add “reuse attempts” to better help avoid user being kicked off on mobile app

### ISSUE THREAD

**Issue by delfme** [supabase/gotrue#1318]
# Bug report the bug

We have a flutter mobile app where sometimes user is kicked off from client coz refresh token was already used. We have opened a support ticket and discussing issue with you guys there. Just thought to also open this ticket to expose an idea that maybe could be implemented to better help avoid this issue clientside. 

CC: @hf , @dshukertjr 

## To Reproduce

Unfortunately our code is closed but we use latest version of supabase-flutter plugin to auth users via otp, with 1m jwt expiry period and 10s reuse interval. No custom code gets in the middle of the auth process.

## Expected behavior

User must be never kicked off on a mobile app.

## Additional context

We are not sure about that, but maybe this is the flow that could cause the issue:
1) user quits mobile app and doesn't open it for hrs. This means that on next access, token must be refreshed
2) at app launch, something goes wrong due to  poor connectivity and the api call fails. On mobile this occurs frequently.
3) user quits app, or maybe internet gets off totally, and the 10s refresh token “reuse interval” passes by before user gets a new auth token
4) user opens app again after some time when internet connection is back and might found himself kicked off, coz refresh token was reused and reuse interval has passed by.

## Idea
What about adding “reuse attempts” ?

It could be set via dashboard along with “reuse interval”. For example, with “reuse attempts : 3” client will have 3 attempts to still get a new access token by using refresh token after reuse interval has passed by. To make the api call more secure, user could pass also the last used access token along with the old refresh token. That would be difficult to hack, yet easy to manage clientside.

**Comment by hf** [comment]
Please refer to this documentation to understand how the reuse detection algorithm works: https://supabase.com/docs/guides/auth/sessions#what-is-refresh-token-reuse-detection-and-what-does-it-protect-from

We are not planning on adding anything else other than what is described there for the foreseeable future. Please make sure your app code handles errors correctly (or open GitHub issues in the relevant libraries if it doesn't):

1. Network errors should be retried by your app, the session shouldn't be removed from storage.
2. Concurrent requests to Supabase Auth / GoTrue should be avoided, make sure you implement this correctly in your app.

Reasons why we do not plan to add reuse attempt counter:

1. It opens up a big security issue. There's no "magic number" for this. It's either a reuse or it is not.
2. There is one case that is now supported (which wasn't previously) by Supabase Auth and that is the case when the client (app) failed to save or receive the response.

I will be closing the issue right now, as what you're experiencing is probably due to synchronization issues in your app or bugs in the client libraries used.

**Comment by delfme** [comment]
👍 will have a look at it
