### ISSUE TITLE
Textlocal SMS OTP not being sent.

### ISSUE THREAD

**Issue by girish-algotech** [supabase/gotrue#1356]
I'm using Textlocal as the SMS provider in order to send SMS OTP for users to signup/login.

SMS sent via Supabase fails with error "Textlocal error: Internal error". There is no additional information in the Auth Logs.

As I'm able to successfully able to send SMS from Textlocal dashboard and through Textlocal API via Postman, so don't think there is any issue at Textlocals end. Have also verified that the Textlocal config in supabase is exactly the same as what I'm using to send SMS successfully from Textlocal API.

Have also checked this file https://github.com/supabase/gotrue/blob/b57c3959789eeea27a3cd7489895aa68a6479e9b/internal/api/sms_provider/textlocal.go and though I'm not proficient in Go seems like the Textlocal api is configured correctly. 

So not sure why sending Textlocal SMS from Supabase fails. Is there a way I can check the request params of the Textlocal API being hit by supabase?

curl of the api request that actually works (have replaced private data with X):
```curl --location 'https://api.textlocal.in/send/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'apikey=XXXXXXXXXXXXXXXXXXXXX' \
--data-urlencode 'message=123456 is your one-time password to your XXXXX account. This OTP is valid only for 5 minutes. Confidential.

A product of XXXXXX Private Limited' \
--data-urlencode 'numbers=91XXXXXXXXXX\
--data-urlencode 'sender=XXXXXX'
```

**Comment by raj-algo** [comment]
We contacted the TextLocal team and they were quick to help.

TextLocal API was failing because of the next line used in the Message Template.

**Original message**
{{ .Code }} is your one-time password to your XXX account. This OTP is valid only for 5 minutes. Confidential. 

A product of xxx Private Limited

**Updated Message**
`{{ .Code }} is your one-time password to your XXX account. This OTP is valid only for 5 minutes. Confidential.%n %nA product of xxx Private Limited`

**Solution**
TextLocal team informed us to use `%n` for the next line while creating the template in TextLocal and while adding it to the Supabase `SMS message`.

We didn't find any documentation on same anywhere, hope this helps others in future.

**Comment by girish-algotech** [comment]
Resolved.

For anyone else who faces similar issue, if your sms template has a new line make sure you add `%n %n` in the template instead of actual new line.

For example for in my case the template was 
```
123456 is your one-time password to your XXXXX account. This OTP is valid only for 5 minutes. Confidential.

A product of XXXXXX Private Limited
```

I modified it to

```
123456 is your one-time password to your XXXXX account. This OTP is valid only for 5 minutes. Confidential.%n %nA product of XXXXXX Private Limited
```

Make sure you modify the template in both Textlocal and Supabase.
