### ISSUE TITLE
Auth hooks updates signed access_token, but not REST response. 

### ISSUE THREAD

**Issue by mr-menno** [supabase/gotrue#1415]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`user_metadata` in access token does not match user_metadata in REST response. 

## To Reproduce

Create auth hook in Supabase to update user_metadata. 
1. access_token JWT contains updated user metadata. 
2. REST response JSON including the access_token misses data in user.user_metadata. 

## Expected behavior

Consistency between REST response and access_token. 

## Other Issue

Gotrue-js issue:

https://github.com/supabase/gotrue-js/issues/852

## System information

- Version of supabase-js: 2.39.3
- Version of Node.js: 20

**Comment by J0** [comment]
Hey! 

Thanks for the query. `getSession` typically checks for a local token which might be out of sync with the recently returned token. If you're looking to obtain an up to date token with custom claims would recommend that you update `app_metadata` in the Auth Hook and use `getUser` to obtain a fresh access token.

Alternatively, you could wait for a refresh event to happen and the new access token should show the claims, providing they were saved to the users table.

Hope this helps

**Comment by mr-menno** [comment]
I’ll try it with app_metadata.

Are you saying the auth hook should update the claim, or should the auth
hook do an upsert on the auth.users table?

**Comment by J0** [comment]
Hey @mr-menno,

Sorry, I spoke with a colleague earlier today who  and realized that I misunderstood this query. The REST response indeed does not return the claim but the signed access token does.  We'll likely add it in the REST response for the next release

Thanks for flagging this!

**Comment by taytzehao** [comment]
would like to take this

**Comment by mr-menno** [comment]
Thanks Joel!  Right now I just created an alternate getSession function in
supabase to inject the decoding of the JWT and overloading the session.user
object.

Would love to keep it beyond user_metadata and app_metadata for any claim
extension.

**Comment by tzehaoo** [comment]
@mr-menno , could you show a precise example of it? Currently, when I run
```bash
const { data2, error2 } = await supabase.auth.updateUser({
    data: { hello: 'world5' }
  })
```
`data2` is undefined. Do you mean this?

**Comment by taytzehao** [comment]
@mr-menno , could you show a precise example of it? Currently, when I run
```bash
const { data2, error2 } = await supabase.auth.updateUser({
    data: { hello: 'world5' }
  })
```
`data2` is undefined. Do you mean this?

**Comment by tzehaoo** [comment]
okay, creating the PR

**Comment by hf** [comment]
Custom Access Token Hook cannot be used to modify the user metadata, which is common with other similar features in other authentication software. There will be a different hook in the future where you could change the user metadata "before sign up" for example.

**Comment by mr-menno** [comment]
This issue is different. The hook already modifies the access token.
However, in the JSON response (which includes the access token), the JSON
response does not line up with any modifications made by the hook to the
token. (This applies to modifications to user or app metadata, or any other
attribute. )

**Comment by gregtbrown** [comment]
I realize this issue has been close, but I am also trying to understand this:

If the hook modifies the token, great, I can decode the token on the server with the secret key, but I can NOT decode the token client-side because I obviously don't want the token secret anywhere near the client.

Here's the scenario:

- Let's say I have a user_type that I want to pull from a DB table and add to the token with a hook.
- This works as-advertised in your example code.
- I can check user_type in the backend for sensitive ops like data access by decoding the token
- But if I ALSO want to use user_type in the frontend for something less sensitive, like enabling a feature, I can't because I have no access to my hook data in getUser() or getSession()
- The only data I DO have access to is app_metadata or user_metadata, neither of which I can change as an admin
- The only other option I see is to make another explicit request to the DB post-login to retrieve the additional user data

So as I understand it, the hook data is only good for one of two things:
- access to protected data in an api call to an edge function (by decoding the token)
- small optimization in a RLS check to avoid querying your custom user data table, for instance, in this example where you `select (auth.jwt() ->> 'user_role')::public.app_role into user_role` instead of just selecting from the user_roles table.  To me this seems like and overly complicated way to achieve the same result (using the hook), but perhaps there is something I'm not understanding.  See:  https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac?queryGroups=language&language=plpgsql
