### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by Yasirunet** [supabase/gotrue#166]
# Improve documentation

## Describe the problem

As far as I know, the Supabase fork of GoTrue might support to Postgres database, while the original repo is only supporting MySQL/MariaDB. But the docs of this repo also stated, that only supported MySQL. 

## Describe the improvement

Is this fork of GoTrue does supported Postgress? If yes, could u please share the relevant `DB_DRIVER` for config? As well as it would be awesome if you guys can share, what things you guys made to make GoTrue compatible with PostgreSQL. Thanks in advance!

**Comment by ph1p** [comment]
Hi @Yasirunet, maybe this file will help you to set up your Postgres database https://github.com/supabase/gotrue/blob/master/hack/postgresd.sh . And yes it should definitely be documented if it is a supported driver.

**Comment by kangmingtay** [comment]
Hey @Yasirunet, sorry for the lapse in documentation! We were really pushing for some features to go out for the launch week in August such as the ability for gotrue to automatically run its database migrations on start. This wasn't a concern in the past because we didn't make any changes to the underlying schema but with the phone authentication feature, we had to add some extra columns to the `users` table. 

> Is this fork of GoTrue does supported Postgress?
That is correct. The DB_DRIVER should be `postgres`. Since the upstream of gotrue by netlify is using `mysql` as the DB_DRIVER, we had to make changes to the initial schema to make it compatible with postgres. In addition, some of the code in gotrue relied on specific mysql dialect which doesn't work for postgres. We had to make those changes too. Hope this helps!

**Comment by Yasirunet** [comment]
Thanks for the reply @kangmingtay. I'll close this issue for now. If I found any problem while I configure gotrue with Postgres I'll raise it separately. It's better if u can update the docs once u get free time. Keep up the great work! ✌

**Comment by mtwichel** [comment]
Hi everyone 👋  I saw the README still says the only suported driver is mysql [here](https://github.com/supabase/gotrue#database).
> `DB_DRIVER` - `string` **required**
Chooses what dialect of database you want. Must be `mysql`.

Should this be changed to `postgresql`?

Thanks for all you do! ❤️
