### ISSUE TITLE
CORS - Allowed origins support

### ISSUE THREAD

**Issue by ChronSyn** [supabase/gotrue#175]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, it appears that all origins are allowed for requests. This potentially means that someone is able to retrieve the URL and anon token from the network tab of a browser dev console, and run the requests elsewhere.

Source:
 - The CORS handler (https://github.com/supabase/gotrue/blob/master/api/api.go#L200) doesn't specify an `AllowedOrigins` parameter (as per https://github.com/rs/cors#parameters), so it appears that all origins are allowed as the default value if not specified is `*`

## Describe the solution you'd like

Provide an env variable which passes `AllowedOrigins` through to the relevant parts of GoTrue (as well), omitting it if not specified so that the default `*` is provided. This could be an independent input field in the dashboard, but implementing the env support would be a good starting point. This would prevent websites outside of the allowed origins from calling into authentication. It may also be preferable to provide such functionality to the other parts of the stack (e.g. REST, storage, etc).

If allowed origin option is specified (dashboard or env), CORS behaviour will limit requests only for those specific origins, otherwise, all origins will be allowed.

## Describe alternatives you've considered

Routing requests through an API is certainly an option, but that would perhaps require further wrapping of requests. For self-hosting, an Nginx proxy in front can handle CORS to all services underneath it, but I feel that providing an option within the core of the stack would be a nicer option.

## Additional context

We were discussing this in 'client side security concerns' thread in the general channel on Discord, with these feature request details mostly mirrored in the 'CORS discussion' thread in the ideas and suggestions channel.

The main concern I have is that resources that are spent serving requests from illegitimate sources (i.e. third-party websites) could be better used serving legitimate requests. Likewise, preventing a third-party front-end from requesting data (e.g. a public table where only SELECT queries are allowed) via REST or even sending an auth request unless they're in the allowed origins list would be desirable in some scenarios.

If this functionality is already available or implemented elsewhere in the stack, could you provide some details and I'll aim to update the docs.

If such functionality isn't needed due to other mechanisms in place, clarification would be much appreciated.

**Comment by kangmingtay** [comment]
Hi @ChronSyn, thanks for raising this issue up! This would definitely be good for developers who want to self-host gotrue without having to set up an api gateway. On our end, we actually have an internal issue to limit this on our Kong api gateway.

**Comment by hf** [comment]
Hey, this issue is not relevant for GoTrue. Let me try to explain why.

GoTrue is an API server written in Go. It does not have TLS support built-in, as it's meant to be placed in front of a proper HTTP reverse proxy such as NGINX, load balancer or other such software or appliance. As such it is not aware about your network configuration and it would be fairly complex to try to do so. Typically this task, again, is left to a proper reverse proxy to fulfill. This includes setting up proper CORS support.

Any existing support in GoTrue for CORS is really just a developer aid, for when you need to quickly test things out. It is not meant to be used as-is in production environments.

However, should you need to setup a more production-ready environment locally, I suggest you use NGINX in front of GoTrue and configure relevant settings there (like TLS, CORS, maximum body sizes, etc). This is a good guide to get you started: https://stackoverflow.com/questions/45986631/how-to-enable-cors-in-nginx-proxy-server

On another note:

> This potentially means that someone is able to retrieve the URL and anon token from the network tab of a browser dev console, and run the requests elsewhere.

This is something we can't control, not with CORS or anything else. A compromised end-user device (which includes users opening up the development console) is not something that can be guarded against, and thus does not fall under the security model. Don't forget that the main purpose behind the CORS mechanism is to prevent cross-origin attacks where unauthorized domains can be using your APIs.

We will take the notion into consideration for the CORS settings we have on the Supabase platform, which may be possible to lock down to only domains you list.

**Comment by aloisklink** [comment]
It might be worth also subscribing to https://github.com/orgs/supabase/discussions/7038, as that has more activity on setting a `Access-Control-Allow-Origin` for Supabase APIs.

It looks like the Data API supports it already: https://github.com/orgs/supabase/discussions/7038#discussioncomment-9942689
