### ISSUE TITLE
OAuth providers seem to have a dependency on email signups being enabled

### ISSUE THREAD

**Issue by darora** [supabase/gotrue#193]
Moving from https://github.com/supabase/supabase/issues/2851#issuecomment-904395347

Google Auth provider refresh token call fails with "400 Unsupported Email Provider".

**Comment by J0** [comment]
# Bug report

## Describe the bug

Bug is appearing after disabling "Enable Email Signup" in dashboard.
I'm using Discord as provider for OAuth.
When supabase-js client is trying to refresh token in react-app instead of getting new token I'm getting this response:

HTTP Code 400 with body:
`{
  "code": 400,
  "msg": "Email logins are disabled"
}`

After enabling "Enable Email Signup" I'm getting token with response.

## To Reproduce

1. Setup via discord sign in
2. Disable "Enable Email Signup" in supabase dashboard
3. Sign in with discord in your app
4. Wait for request

## Expected behavior

Getting new token with request.

## System information

- Version of @supabase/supabase-js: 1.22.5

**Comment by hf** [comment]
Hey everyone, please take a look at this comment by @kangmingtay on why we're not able to devote more time on this for now. https://github.com/supabase/gotrue/pull/414#issuecomment-1238321323

**Comment by hf** [comment]
Please refer to #214 to track this issue further.
