### ISSUE TITLE
Support Sign in With Apple with AuthenticationServices

### ISSUE THREAD

**Issue by catlan** [supabase/gotrue#198]
# Feature request

On Apple platforms, Sign in with Apple ID should be done with the [AuthenticationServices](https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidcredential?language=objc) framework in native apps. Currently it is not possible to use this, we also have an issue open in [gotrue-swift](https://github.com/supabase/gotrue-swift/issues/4) but it seems the server itself would required some changes for this to work.

## Describe the solution you'd like

@thecoolwinter:
> Right now I think the GoTrue server would need to be modified to accept and validate the JWT from the AuthenticationServices framework and send back a GoTrue JWT.

**Comment by thecoolwinter** [comment]
[Apple's docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user) give a little more detail as to what's required to make the AuthenticationServices framework work

Basically, only 2 modifications would need to be made to the gotrue server:
1. Add a `POST /authorize/apple` *(or another path)* endpoint what accepts: JWT identity token, access token, nonce, apple ID, and email.

This endpoint needs to verify the identity token against Apple's servers and then exchange the access token for an refresh token as in the graphic from the [docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user). It should then create a user if needed, otherwise it needs to store the refresh token for later verification. The apple ID would be nice to store as well, probably where other OAuth information is stored. It should also return a GoTrue JWT. 

Also important in this step is checking the `nonce` given from the client. This should be verified against the `nonce` field in the identity token to prevent replay attacks.

2. When verifying this user: Grab the refresh token from `1` and verify it against apple's servers using the [validation](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens) endpoint. This can only be done once a day, so we'd need to store both the refresh token and the last validated date in the user object. If it's valid, generate a normal GoTrue JWT.

This step takes care of the case where a user removes their account through their Apple ID. The next time we go to refresh their token, it should be invalid and we consider the user signed out.

**Comment by kangmingtay** [comment]
Hey @thecoolwinter, @catlan, thanks for the feedback! We are currently working on it and we actually have a PR [here](https://github.com/supabase/gotrue/pull/189) for this! 

We're in the midst of testing it thoroughly and doing abit of refactoring before we merge this in.

**Comment by catlan** [comment]
That's great to hear, @kangmingtay!

**Comment by thecoolwinter** [comment]
Awesome! Glad to hear it! I'll watch that PR so we can make changes to the swift repo when it becomes available.
