### ISSUE TITLE
Refresh token reuse detection

### ISSUE THREAD

**Issue by Mimameid** [supabase/gotrue#213]
# Feature request

## Is your feature request related to a problem? Please describe.

Using invalidated refresh tokens doesn't have any consequences.

## Describe the solution you'd like

Using an invalid refresh token should invalidate every refresh token and access token descending from the original refresh token.

## Additional context

This can protect the application from compromise and replay attacks.

**Comment by kangmingtay** [comment]
Hey @Mimameid, hmm just to clarify, does using an invalidated refresh token return an access token? Or is there nothing returned? A refresh token is only valid for one-time use and is revoked after it's used. Once the refresh token is revoked, the `revoked` column in the `auth.refresh_tokens` table is set to true and the refresh token can no longer be used.

> Using an invalid refresh token should invalidate every refresh token and access token descending from the original refresh token.

Hmm I feel that this might not be a good enhancement to add because an attacker can exploit it by constantly sending invalid refresh tokens to the api, which will result in blocking an actual user from obtaining an access token / a valid refresh token.

**Comment by Mimameid** [comment]
Hey @kangmingtay, not it does not. It just returns an error message, telling that the refresh_token is invalid. 

The problem I see is, that not only replay attacks would be prevented by this, but also a compromised refresh token (though in this case we could assume that the user has bigger issues) would give the attacker unlimited access, without anyone noticing.

Referring to this: https://datatracker.ietf.org/doc/html/rfc6819#section-5.2.2.3

**Comment by kangmingtay** [comment]
Ah ok I see where you're coming from, this is a good point and definitely will help to improve the security of gotrue overall. Currently, even if a refresh token is revoked, the access token will still be valid for the duration of the `GOTRUE_JWT_EXP`. So what we'll need to do is to revoke any access tokens tied to a revoked / expired refresh token. 

However, we don't have to revoke every refresh token descending from the original refresh token because a new refresh token isn't dependent on the old one. The refresh token is generated uniformly randomly using go's native crypto library.

**Comment by Mimameid** [comment]
Hey @kangmingtay, if descendant refresh tokens aren't revoked, there is no telling, if there was a malicious usage of the refresh token. The article says:
"...in case of such an access attempt the valid refresh token and the access authorization associated with it are both revoked.".

In other words: There should only be one refresh token valid. If an invalid refresh token, the valid token is descending from, is used, the valid one should be invalidated.

**Comment by kangmingtay** [comment]
Got it! Found a great resource [here](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/#Refresh-Token-Rotation) by Auth0 that we can reference along with the RFC to implement better practices for managing refresh tokens on gotrue.

**Comment by kangmingtay** [comment]
@Mimameid thanks for the feedback, we'll will be shipping this out soon in the next release!
