### ISSUE TITLE
API compatibility with netlify/gotrue

### ISSUE THREAD

**Issue by markhaehnel** [supabase/gotrue#219]
Do you have or/and intend to keep the public API surface compatible with netlify/gotrue?

I'm writing a administration UI for gotrue and thought about addnig compatibility for your fork too.

**Comment by kangmingtay** [comment]
Hey @markhaehnel, we have a RFC [here](https://github.com/supabase/rfcs/pull/2) and the current plan is to unfork gotrue from netlify's upstream version because our fork has diverged quite abit. You can checkout the link I've attached for a detailed explanation on the tradeoffs of this decision and the current disparities with the upstream repo.

**Comment by markhaehnel** [comment]
Hi @kangmingtay. This is a reasonable decision even if it's not the best for the open source community. Especially because Netlify doesn't really maintain their GoTrue repository well, imho.  With missing documentation and half broken features.

I'm looking forward to the further development of your fork! 👍🏻
