### ISSUE TITLE
feat: Indicate that confirmation is required in response

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#227]
thread here https://github.com/supabase/gotrue-dart/issues/32#issuecomment-906639397 and https://github.com/supabase/gotrue-js/issues/126

showing that at the API level it's not clear that a signUp was successful and is awaiting email/phone verification

perhaps all responses should have a field `data.awaitingEmailVerification` and `data.awaitingPhoneVerification` with corresponding bools

**Comment by awalias** [comment]
any thoughts on this one @thorwebdev ?

**Comment by darora** [comment]
I'd suggest adding a more general 'status' enum field on the 'profile' or 'status' endpoint response.

**Comment by i-pip** [comment]
pilling on @darora's suggestion, maybe something like `{verified: true/false}`? or `{phoneVerified:true/false}` and `{emailVerified:true/false}` - doesn't even have to modify the user model, can be implemented at API level since there are already `PhoneConfirmedAt` and `EmailConfirmedAt` fields on the `User` model

**Comment by hf** [comment]
If there's a valid date in the `user` object returned on the `email_confirmed_at` and/or `phone_confirmed_at` fields, then the user has confirmed their email and/or phone number.
