### ISSUE TITLE
SAML SSO Support

### ISSUE THREAD

**Issue by Emsu** [supabase/gotrue#244]
# Feature request
I'd like to support SAML SSO through services such as OneLogin, Okta, Ping Identity, etc.

## Is your feature request related to a problem? Please describe.
Enterprise clients want to use these providers for authentication and is key for an application trying to service larger customers

## Describe the solution you'd like

I'd like to be able to manage and upload SAML certificates and allow customers to login through SAML SSO.

## Describe alternatives you've considered

There aren't very many industry alternatives to SAML SSO for enterprise clients. The only alternative if the feature isn't supported is to not use Supabase Auth and use Firebase or Auth0 or roll your own.

## Additional context

No other context I can think of. Feel free to ask any questions about the use case and I can provide more details.

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson) 🚀

**Comment by kevinmlong** [comment]
Any progress on this? Very much interested in hooking Up Okta to Supabase and RLS.

**Comment by aantn** [comment]
Likewise.

**Comment by hf** [comment]
Status update: this can be used on self-hosted now, but we're working on getting everything set-up for projects early next year. Please express interest as a comment or emoji here, we'll reach out to you when we have a beta.

**Comment by aantn** [comment]
We want this ASAP!

**Comment by aantn** [comment]
To clarify our requirements, we need to use different SSO providers for different users in the same Supabase project. (Depending on which one of our customers they belong to.) Will this be supported?

This means that our Supabase project will have, for example, multiple Okta SSO providers for different email domains.

**Comment by J0** [comment]
Hey all,

Please see [the SAML guide](https://supabase.com/docs/guides/platform/sso) on how to enable sign in with SSO on the `supabase.com` 

If you're looking to build an application using Supabase which supports SSO please emote on @hf 's comment above for updates

**Comment by fortenforge** [comment]
Are there any instructions anywhere on how to use SAML with self-hosted supabase?

**Comment by hf** [comment]
Local development with SAML is a bit tricky, mainly because all the popular identity providers don't allow you to use localhost, or a non-HTTPS endpoint.

Self-hosting is supported, but we don't have docs for this yet. Again this is because you need to securely expose GoTrue to the internet behind HTTPS. It's not particularly easy nor is there one way to do thus. In any case the short story is this:

There are some admin APIs related to SAML you should call with an admin JWT. You can find them in the [openapi.yaml](https://github.com/supabase/gotrue/blob/master/openapi.yaml) spec. (Put this file in editor-next.swagger.io for a better view.)

With these you can create a SAML connection. It's basically what the Supabase CLI uses under the hood. We also have a Terraform / Pulumi provider we use internally that may be helpful, but it's still in the early stages: https://github.com/supabase-community/pulumi-gotrue

That's kind of it. Let me know if you have any questions.

**Comment by fortenforge** [comment]
Thanks, that's very helpful. I'm assuming the admin APIs are a POST request to `/admin/sso/provider`. Is there anything else? Also, is an Admin JWT the same as the service account JWT?

**Comment by kangmingtay** [comment]
> I'm assuming the admin APIs are a POST request to /admin/sso/provider

We support `GET` , `PUT` and `DELETE` methods as well, you can take a look at the [openapi spec](https://github.com/supabase/gotrue/blob/master/openapi.yaml) for the full list of params. 

> Also, is an Admin JWT the same as the service account JWT?

If you're using Supabase, the admin JWT is the service key. If you're self-hosting gotrue, an Admin JWT needs to have a `role` claim with a value that has been set in the env variable `GOTRUE_JWT_ADMIN_ROLES`

**Comment by kangmingtay** [comment]
hey everyone, i'm closing this issue since we support SAML SSO already. Check out our blog post and docs here:
1. [Blog post](https://supabase.com/blog/supabase-auth-sso-pkce)
2. [Docs](https://supabase.com/docs/guides/auth/sso/auth-sso-saml)
