### ISSUE TITLE
Custom email templates are not working

### ISSUE THREAD

**Issue by jamesallchin** [supabase/gotrue#278]
# Bug report

## Describe the bug

1. Enable Custom SMTP (in case relevant I am using SendGrid SMTP Gateway)
2. Create a custom email template for "Confirm Signup"
3. Use a custom `subject` and custom `body`
4. Save these changes
5. Refresh the dashboard and confirm the changes are saved correctly - all good

The email that gets delivered uses the new custom `subject` but the `body` is the default supabase template

## Expected behavior

The email that gets delivered should use the custom `body` as well (currently only the `subject` is being used). 

## Screenshots

![image](https://user-images.githubusercontent.com/6538573/141449916-30225ab8-7dcf-48d9-b231-27cbac2ffca0.png)

## System information

- N/A - standard Supabase cloud setup

**Comment by awalias** [comment]
error is from the mailme package here: https://github.com/netlify/mailme/blob/876c043aa349526e4372914d5ee416ec1de242f1/mailme.go#L163

**Comment by jamesallchin** [comment]
thanks @awalias for looking into this - really appreciate it

**Comment by dthyresson** [comment]
Hi @jamesallchin. Quick update - the reason the Confirmation Email template failed was that it could not be parsed due to invalid template token replacement. Basically, the template was invalid, but unfortunately a) the UI did not let you know when saving that there was an issue and b) the log mentioned above was not helpful in diagnosing the problem; it simply said, could not fetch template.

I'll be writing up some issues to help make the documentation and the template admin UI clearer for what tokens and the format are allowed in each template type. And, also an issue to look into validating the template when saving -- therefore letting you know the template has a problem and it won't save.

For you particular Confirmation Email, the following token replacement variables are allowed:
* `SiteUR`
* `Email` 
* `ConfirmationURL`

The problematic variable is in this line:

```
 alt="{{{preheader}}}" border="0" width="186" 
```

There are two problems here:

* variable replacements are done with 1 enclosing braces, ie:

```
<p><a href="{{ .ConfirmationURL }}">Log In</a></p>
```

... and this has three `{{{xxx}}}`

* the variable `prerender` is not a valid variable option for this template type

I think `prerender` is being used in this alt tag, but more often it's used as a css style/class:

```
<span class="preheader" style="color: transparent
```

You you try to update your template and correct that `alt` tag to be a standard test attribute value and let me know if the email is sent out as you expect?

Thanks for reporting and it will help others once the docs get updated.

**Comment by dthyresson** [comment]
> I’m having the same problem.

Hi @jtparrett Could you share your template as well -- or check for the template variables and the use of braces? Perhaps this is the same issue that @jamesallchin had with in invalid template.

FYI - The list of valid template variables per each email template type can currently be found in: https://github.com/supabase/gotrue#e-mail

Typically these are:

```
 SiteURL, Email, and ConfirmationURL
```

But `NewEmail` is available on email address changes.

**Comment by jamesallchin** [comment]
@dthyresson i can indeed confirm that this issue is fixed if I remove the erroneous `{{{preheader}}}` tag. 

Many thanks for investigated. I agree with you would make a lot of sense that there is pre-validation of the template on save. 

And also would be very useful to get the auth logging fixed in the dashboard.

**Comment by fincha** [comment]
same here, using this template:

```
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bestätigen Sie Ihre E-Mail-Adresse</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <table style="width: 100%; background-color: #f4f4f4; padding: 20px;">
        <tr>
            <td style="text-align: center; padding: 20px 0;">
                <h1 style="color: #4a4a4a;">Willkommen bei BeautiQ!</h1>
            </td>
        </tr>
        <tr>
            <td style="background-color: #ffffff; padding: 20px; border-radius: 5px;">
                <p>Hallo {{ .Email }},</p>
                <p>Vielen Dank für Ihre Anmeldung. Um Ihr Konto zu aktivieren und Ihre E-Mail-Adresse zu bestätigen, klicken Sie bitte auf den folgenden Button:</p>
                <p style="text-align: center;">
                    <a href="{{ .SiteURL }}/confirm-signup?confirmation_url={{ .ConfirmationURL }}" style="display: inline-block; padding: 10px 20px; background-color: #007bff; color: #ffffff; text-decoration: none; border-radius: 5px;">E-Mail bestätigen</a>
                </p>
                <p>Oder kopieren Sie diesen Link in Ihren Browser:</p>
                <p style="word-break: break-all;">{{ .ConfirmationURL }}</p>
                <p>Falls Sie den Button nicht anklicken können, geben Sie bitte diesen 6-stelligen Code ein:</p>
                <p style="font-size: 24px; font-weight: bold; text-align: center; letter-spacing: 5px; color: #007bff;">{{ .Token }}</p>
                <p>Dieser Link und Code sind aus Sicherheitsgründen nur für begrenzte Zeit gültig.</p>
                <p>Wenn Sie diese E-Mail nicht angefordert haben, können Sie sie ignorieren.</p>
                <p>Bei Fragen stehen wir Ihnen gerne zur Verfügung.</p>
                <p>Mit freundlichen Grüßen,<br>Ihr [Ihr Unternehmen] Team</p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center; padding: 20px; font-size: 12px; color: #666;">
                <p>Dies ist eine automatisch generierte E-Mail. Bitte antworten Sie nicht darauf.</p>
                <p>© {{ current_year }} [Ihr Unternehmen]. Alle Rechte vorbehalten.</p>
                <p><a href="{{ .SiteURL }}" style="color: #007bff; text-decoration: none;">Unsere Website besuchen</a></p>
            </td>
        </tr>
    </table>
</body>
</html>
```

**Comment by mfrischbutter** [comment]
@fincha 

Unfortunately, e-mails are not used if wrong variables are used. 

Remove the variable `{{ current_year }}` and the e-mail should be sent with this template.
