### ISSUE TITLE
RFC: sending JWT in header

### ISSUE THREAD

**Issue by thorwebdev** [supabase/gotrue#279]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently when redirecting from GoTrue to site url we send the token as fragment which isn't accessible on the server, meaning we have no ability to read the token in a server-side auth route for example, which is why we currently need the AJAX request to set our auth cookie: https://github.com/supabase/supabase/blob/master/examples/nextjs-with-supabase-auth/pages/index.js#L19-L31  which isn't an ideal experience.

## Describe the solution you'd like

We should make the JWT accessible server-side so that users can set their site URL to a server-route (e.g. with nextjs /api/auth) where they set their application auth cookie before the page is rendered to avoid unwanted side effects.

I think the easiest way would be for us to always set the cookie header, which is currently only set conditionally, e.g. https://github.com/supabase/gotrue/blob/master/api/verify.go#L127-L131 but I'm not sure if there is any downside to always sending the Cookie header. If not, we could just remove the condition and always set it.

## Additional context

For example, Auth0 sets the JWT in a request header when they redirect to your return URL:

```js
// console.log(req)
{
// ...
  url: '/api/callback?code=KKo1d_njmlNx9Czw6fK_iiIMpPigpSyWUphj2RnQHlh1Z&state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9',
  method: 'GET',
  query: {
    code: 'KKo1d_njmlNx9Czw6fK_iiIMpPigpSyWUphj2RnQHlh1Z',
    state: 'eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9'
  },
  [Symbol(kHeaders)]: {
    host: 'localhost:3000',
    connection: 'keep-alive',
    'cache-control': 'max-age=0',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-user': '?1',
    'sec-fetch-dest': 'document',
    'sec-ch-ua': '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-GB,en;q=0.9,de-DE;q=0.8,de;q=0.7,sv-SE;q=0.6,sv;q=0.5',
    cookie: 'nonce=CMsL6Gf_6--6BWvmVoa6dN5JjEQfk-3akVAsJOFSLww.ci2MKZ6bOPG0mVKUdIn4AYuc5V6cGTt5ZJCm1Wpqp-c; state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.8z0o6e3gtALtDo9xVT-Rj6kxubkVXSV_jCNlggLV0CQ; code_verifier=TlQbgMQi55G3RFFm_OgD0Iv6KMoz9gcRCqu_fmXxVcA.eCfeYKoksLKLiPgqv7Iovfvzr9x3eE9Fb1yPHNvCeZs'
  },
// ...
}
```

The cookie header is then read server-side in the callback route (https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/handlers/callback.ts#L38-L56) to set up the OpenID issuer which makes requests to Auth0. I don't think we need to whole OpenID issuer (just yet) but I think we should make the JWT accessible server-side to facilitate the expected DX.

**Comment by thorwebdev** [comment]
Correction, Auth0 does not set the JWT in the header but rather the params needed to create the OpneID issuer client I guess?

**Comment by kiwicopple** [comment]
cool - it looks like there are 2 possibilities

## Option 1: Follow Auth0 flow

Follow the Auth0 flow. In this case it looks like we need to send some additional data (`state` param, `nonce` etc), which is then used to verify and create a new session.

## Option 2: Send the session directly.

Send the session data in a cookie, as you point out [here](https://github.com/supabase/gotrue/blob/master/api/verify.go#L127-L131). This is very similar to how we attach the session to the [URL fragment](https://github.com/supabase/gotrue/blob/1dddc248fb820e638f0d54b9d51c2803295b5c1d/api/verify.go#L139), which is inaccessible to the server.

questions: 

- if the cookie is set on a GoTrue server it should be accessible on a `xxxx.supabase.co` domain only right? Does this need to be another header/method of attaching the session info?
- are there any security concerns around the session data leaking if it's in a header? I guess it's no less secure than the URL fragment, which is already a part of the OAuth spec

**Comment by thorwebdev** [comment]
I think option 2 is the low-hanging fruit here. We can think about option 1 later down the road.

> if the cookie is set on a GoTrue server it should be accessible on a xxxx.supabase.co domain only right? Does this need to be another header/method of attaching the session info?

Correct, the user's server can't access the cookie, but it can access the cookie header of this specific request. And we'd then simply extend our existing `supabase.auth.api.setAuthCookie(req, res)` functionality to look for the JWT in the header and then set the user's application cookie which is then used for subsequent requests throughout their app 👍

> are there any security concerns around the session data leaking if it's in a header? I guess it's no less secure than the URL fragment, which is already a part of the OAuth spec

Yah, that's exactly what I'm looking to confirm. I *think* it's fine as long as everything is happening via HTTPS? But also not an expert here unfortunately.

**Comment by thorwebdev** [comment]
Oh, and lastly we would also need to enable the gotrue server to accept form submit requests for email sign-in and for sign-out requests. These requests will then also need to be redirected back to the site url. That way we can ensure that all sign-up/sign-in/sign-out requests go through the user's `/auth` server route to update the application state.

**Comment by kiwicopple** [comment]
I think the form submissions are an immediate go-ahead. There are no security concerns there - in fact I think that's how netlify's version works

**Comment by inian** [comment]
> And we'd then simply extend our existing supabase.auth.api.setAuthCookie(req, res) functionality to look for the JWT in the header and then set the user's application cookie which is then used for subsequent requests throughout their app

We will need to make this cookie http-only in gotrue-js. Currently it [is not](https://github.com/supabase/gotrue-js/blob/1a4e81d6f44593ca726172e1daaf8473df5618e1/src/GoTrueApi.ts#L478), which makes it less secure than just using local storage. 

> are there any security concerns around the session data leaking if it's in a header?

Usually the token is sent in the hash, so that the server _doesn't_ get access to it. But since the whole point here is to get the server access to the jwt, I think its fine sending it in the header.

**Comment by thorwebdev** [comment]
> We will need to make this cookie http-only in gotrue-js. Currently it is not, which makes it less secure than just using local storage.

This is part of the `setAuthCookie` of the `auth.admin` namespace which only works server-side and sets an http-only cookie via the user's server-side environment: https://github.com/supabase/gotrue-js/blob/master/src/lib/cookies.ts#L134

**Comment by inian** [comment]
Ah didnt dig into the serializeCookie function - this is perfect then!

**Comment by thorwebdev** [comment]
We should also figure out https://github.com/supabase/supabase/discussions/889 as part of this.

**Comment by ryanhiebert** [comment]
If I'm understanding the intended implementation of option 2 correctly, a notable downside is that there would be no way for this to work if Javascript were disabled on the client side. I'm not yet fully acquainted with all of how GoTrue works, so there's room for me to be missing something obvious to others, but I think it would be ultimately preferable if client-side javascript were not required to use Supabase. With RLS and authentication, ISTM that Supabase would still have a lot to offer without client-side Javascript, so it seems ultimately suboptimal for it to require it in all scenarios, especially if the goal is to enable the server-side.

**Comment by jackmerrill** [comment]
> If I'm understanding the intended implementation of option 2 correctly, a notable downside is that there would be no way for this to work if Javascript were disabled on the client side.

I'll have to agree here-- I'm trying to make a Javascript-less app with Supabase on the backend (through an API of course), so sending the JWT and whatever other info in a header would make server-side authentication so much easier.

**Comment by florianlouvet** [comment]
I believe solution 2 would work with no client-side JS. If I understand correctly, the idea is to set the auth cookie in the redirection made by gotrue. If the cookie is set this way, your future requests to your server would contain the authentication cookie. You could then use this token to make your server-side requests to supabase.

Is there any progress on this issue? Did someone already take a stab at it?

**Comment by hf** [comment]
Hey everyone I'm on the Supabase Auth team here to shed some light on this issue.

We don't want Supabase Auth to rely on cookies for authentication and authorization. It is common in the industry now to use the concept of access and refresh tokens as the preferred mechanism for authenticating and authorizing a user in an application. Cookies are a relatively browser-centric technology that does not fit well with non-browser applications such as native mobile apps, CLI and desktop apps, apps on TVs and IoT devices.

Therefore GoTrue does not really use cookies (although there is some old code that issues them). Developers should not rely on those cookies for any purpose.

That being said, cookies are a great way to convey the access and refresh tokens in web apps, especially for cases where the application is not a SPA and has a server component that requires some user authorization to take place. This is becoming increasingly popular with server-side rendering frameworks, and is traditional in server-based (Django, Rails, PHP, ...) web apps. Here's a snippet of code you can use to extract the access and refresh tokens from within the SPA and set it as cookies on the origin where your app is hosted:

```typescript
supabase.auth.onAuthStateChange((event, session) => {
  if (event === "SIGNED_OUT" || event === "USER_DELETED") {
    // delete cookies on sign out
    const expires = new Date(0).toUTCString();
    document.cookie = `my-access-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
  } else if (event === "SIGNED_IN" || event === "TOKEN_REFRESHED") {
    const maxAge = 100 * 365 * 24 * 60 * 60; // 100 years, never expires
    document.cookie = `my-access-token=${session.access_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=${session.refresh_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
  }
})
```

We are aware about the problems with having a redirect-style flow to get back the access and refresh tokens issued for a login session, however this flow does work for the majority of use cases today. Both browser and native mobile apps use the concept of URLs to finish authentication flows.

An alternative to this flow which we are keen on implementing is the [Proof-Key Code Exchange method (PKCE)](https://www.oauth.com/oauth2-servers/pkce/) that has multiple security benefits and also supports a larger set of use cases including server-only, desktop and CLI apps. There are no concrete timelines for this as I write this comment, but it is relatively high on our priority list.

Unfortunately, this style of authentication does assume a rich client -- one that is able to execute code instead of present static markup. Thus it does not support browser based apps without JavaScript. GoTrue and Supabase Auth are just not suitable for that type of authentication, and it is probably better to look for an alternative.

**Comment by jackmerrill** [comment]
> While it is your right to write off customers like this if you'd prefer not to have them, I want to make sure that you understand what I think might be a reasonable alternative.

Agreed. I completely stopped using Supabase Auth and made a custom solution (still using Supabase) to do user authentication. I had to do this as I was moving my app to full SSR for better performance (big app, JS payloads were huge). 

> Rather than write off customers that wish to lean into progressive enhancement, you may be able to reasonably retain them by permitting switching the # to a ? in the redirect url from Supabase auth.

This is a _much_ more optimal solution. I had even opened an issue for this (#472) but it was dismissed for security reasons (for good reason). Due to this, even having a warning about security could be optimal (as most users that would do this, would know what they're doing, and likely just using SSR like I was).

I am really hoping this RFC passes. We've effectively gone full-circle with web-apps, going from "JS hydration is the future" back to "Server-side rendering is the future". Supabase should be able to adapt to whatever the user case may be.

**Comment by ryanhiebert** [comment]
> We originally switched to params but realised that it might not be as secure as # because params are sent to the server and can be modified in transit so we switched it back

@jackmerrill this is from the ticket you linked. The point about it being modified in transit seems wrong unless the client is compromised (where the fragment would be no better) or the site is not using HTTPS (where the scripts themselves can be compromised on the way to the browser).

The further concern that I've heard in the past is that servers will often log URLs, so if they contain a long-lived secret that could be an unnecessary exposure. This seems to me to be a server configuration challenge, not a Supabase vulnerability; but its a common enough one that I can find some utility in a single-use token approach instead of sending the JWT directly in the URL.

**Comment by ryanhiebert** [comment]
With the recent release of server-side rendering docs, we have [confirmation](https://supabase.com/docs/guides/auth/server-side-rendering#understanding-the-authentication-flow) that the logging concern is their stated concern with merely putting the authentication token in querystring parameters.

What I have done in the past to address this concern is to have a one-time exchange secret that the receiver, whether client or server, could use to obtain the JWT. But once that token is used, any other party attempting to use the same token would fail, addressing the concern of secrets being logged. This mode of operation means that any attempt to re-use a token will either (a) fail or (b) cause loud errors for the legitimate party attempting to use the token.

While I don't expect implementing this suggestion is likely to be very high on the priority list, would the Supabase team be open to considering a pull request implementing this mode of operation? I don't have a good sense of what kind of challenge that would be to implement, but if the Supabase team is willing to encourage that type of contribution, then at least those who care about this can know that there is a potential path to a solution.

**Comment by ryanhiebert** [comment]
I've recently done a fair bit of (re-)digging into how OAuth 2 and OpenID connect work. GoTrue has some trappings that connect it to OAuth2 as a provider in additional to being an OAuth client for many other providers. Particularly, it implements a `/token` endpoint that is compatible with OAuth 2, for `refresh_token` and `password` grants.

Further, looking at the examples from the server-side rendering docs, it appears that the redirection that is implemented also follows patterns that seem strongly inspired by OAuth 2 [implicit grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.2), but where the oauth flow is not triggered by the client. Of particular note is that implicit grant is specified to use URL fragments to communicate. So contrary to my request, I applaud the Supabase for not doing as I preferred. I was wrong.

So where does that leave those of us who would like to see Supabase have a story for sites that might be better served by _avoiding_ client-side Javascript, or at least allowing its absence?

First, I'll note that OAuth 2's Implicit Grant is now [officially discouraged](https://oauth.net/2/grant-types/implicit/) by the OAuth 2 working group. This is not to say its insecure, but that the reasons that motivated this approach exist at all (Javascript clients, primarily) are no longer major consideration, and that the `authorization_code` grant is generally better even for Javascript clients.

With that in mind, ISTM that there would be real value in implementing something analogous to the `authorization_code` grant, that would return a single-use authorization code that would be used at the `/token` API endpoint to obtain access and refresh tokens. This _is_ expected to be returned in the URL in the OAuth 2 spec, and therefore could be used by either the server or the client, as appropriate for the individual case, and wouldn't fall prey to the replay attack challenges. An interesting benefit that the OAuth 2 implementers note is that this gives additional confidence that the access and refresh tokens are actually received by the client, where implicit flow does not confirm that.

That all seems like a fairly large job, with some significant changes required in GoTrue. A worthwhile direction, but one that I wouldn't know how anybody might wish to prioritize.

**Comment by hf** [comment]
Hey @ryanhiebert,

Thank you for your suggestion and opinion. It really means a lot to us.

PKCE (`authorization_code` grant) is very high up on our priority list. Today we're finishing up with [Launch Week 6](https://supabase.com/launch-week) and will start planning our next steps in the coming days. At this time we don't publicly share our roadmaps but we hope to make some progress towards this in the next 2-3 months.

**Comment by thorwebdev** [comment]
@dutchdata it is possibly to do without any client-side JS by utilising PKCE: https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr

**Comment by hf** [comment]
Closing this as Supabase Auth itself is more of an API server, and you can use custom storage adapters or even service workers to achieve this functionality.
