### ISSUE TITLE
Allow OTP sending via email

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue#290]
one user is requesting X digit pin numbers to be sent via email instead of SMS

use-case is desktop app (electron), so that users don't get sent to chrome before redirecting back to the app

would also be useful for mobile users

**Comment by liaujianjie** [comment]
Additional use case to support this feature:

Some of our users browse our site and browse emails with different devices. The current magic link implementation doesn't authenticate the user on the device which the sign in email was requested from.

**Comment by J0** [comment]
Hey! 

@liaujianjie, @awalias has this issue been resolved?

**Comment by liaujianjie** [comment]
> Hey
> 
> @liaujianjie, @awalias was just browsing through the open issues when I saw this. Has this issue been resolved or is it being actively worked on?

I'm not working on it. Maybe @awalias or @kangmingtay would know the status of this issue.

**Comment by kangmingtay** [comment]
I haven't started working on this yet, but i can add this next since there seems to be quite abit of demand for it!

**Comment by kangmingtay** [comment]
Off the top of my head, there are a few possible ways we can implement this:
1. Add a `sendOtp` param to the signup / magiclink endpoints. If it's set to true, we send an otp instead of a confirmation link.
```bash
# POST /signup
{
  "email": "user@email.com",
  "password": "test", 
  "sendOtp": true
}
```

2. Make the change within the internal gotrue config such that it can be set via the supabase dashboard (or the gotrue env vars if self-hosted). 

Other considerations:
(1) would be more flexible than (2) since it provides more flexibility for the developer to choose when to send an otp over a confirmation link (although i'm not too sure what are the potential use-cases here). However, if there are additional custom verification steps after entering the otp, then this interface might expose a potential vulnerability since the `sendOtp` flag can easily be changed on the client-side. 

An attacker can just hit the api directly and set `sendOtp` to false to trigger a link being sent instead. 

Feel free to let me know what you guys think! Or if there's a better way to do it. 

PS: I'm open to renaming the param too, right now, `sendOtp` is the best i can think of :)

**Comment by J0** [comment]
Hey Kang Ming,

Thanks for the detailed response! Was actually thinking of working on it as I'd like to familiarize myself with the GoTrue codebase but seems like you're on top of things. Will look for other suitable issues.

If you'd be okay with it, do you mind tagging me on the PR though? Would love to take a look.

**Comment by liaujianjie** [comment]
Is it possible to have both the confirmation link _and_ the OTP in the same email? I imagine the sudden switch from confirmation links to only OTP would be quite jarring for our end-users. It'll be nice if as a user, I am a able to choose if I want to sign in via the confirmation link or to enter the OTP.

Suggested new default template for such a scenario:

```
<h2>Magic Link</h2>

<p>Click this link to login:</p>
<p><a href="{{ .ConfirmationURL }}">Log In</a></p>

<p>Or copy enter this OTP to login: {{ .Code }}</p>
```

**Comment by liaujianjie** [comment]
Somewhat tangential question:

Is it possible to also use n-digit pin numbers as confirmation tokens? That way we OTPs _are_ confirmation tokens. Then, OTPs and magic links can share an internal implementation. However, I'm not sure how much of security risk that reducing the entropy of the refresh token is considering SMS OTPs are already using it.

**Comment by kangmingtay** [comment]
> Is it possible to also use n-digit pin numbers as confirmation tokens? 

Hmm i think there might be a security concern here. With magic links, gotrue can only identify a user by the confirmation token from the query param. So it has to have a high enough entropy such that a collision is near impossible. 

With OTPs, gotrue requires either an email or phone number to be sent as well in the POST request body so it can identify the user the otp was intended for. The email or phone number acts as a namespace in some sense.

We can't do the same for magiclinks because they have to be GET requests so we can't send the email / phone number in the query param.

**Comment by kangmingtay** [comment]
> If the above is possible, we could even expose APIs to allow devs to generate OTPs/confirmation tokens as an admin API.

Good idea! I think this is still possible for otps, we currently have a /admin/generateLink endpoint to generate magic / invite / recovery links.

**Comment by liaujianjie** [comment]
> With OTPs, gotrue requires either an email or phone number to be sent as well in the POST request body so it can identify the user the otp was intended for. The email or phone number acts as a namespace in some sense.

Right, thanks for the explanation! Does this also mean that it would still be possible if the confirmation URL also includes the email or phone number to identify the user? "Possible" here means (1) the likelihood of clash is near-zero, and (2) the reduced entropy would not be a security concern.

**Comment by kangmingtay** [comment]
Yup it's still possible if we pass the email / phone in the confirmation url because those fields are unique in the db. 

However, based on [OWASP](https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url), it's recommended not to pass sensitive information in the query param.

**Comment by awalias** [comment]
closing as duplicate of https://github.com/supabase/gotrue/issues/264
