### ISSUE TITLE
signUp error not returning both email and password error

### ISSUE THREAD

**Issue by aquaductape** [supabase/gotrue#323]
# Feature request

For signUp error if both email and password are invalid, then the error should contain some useful data that both email and password are invalid, currently only shows password that is invalid.

## Example

```
const { user, session, error } = await supabase.auth.signUp({ email: '', password: '' });
```

## Expected behavior
Either error message property contains both password and email `message: 'Signup requires a valid password and email'` or error has different properties to map to specific errors such as passwordError or emailError.

## Actual behavior
Error message just contains password error even though both email and password are both invalid.

## Why
This makes it easier to display the error UI in the form and leads to better experience. Currently when user just submits with empty form where email and password inputs are empty, only the password error can be displayed which is odd visually.

**Comment by kangmingtay** [comment]
Hey @aquaductape, this isn't really an issue IMO, this is because the password is being checked before the email. Like @kiwicopple mentioned, we still do some minimal validation in gotrue but the client-side should be responsible for sanitising the form inputs before sending them to the API. 

Implementing this for other endpoints with more parameters isn't trivial as we have to have custom error messages for each permutation of query parameters sent in the request. 

If I didn't miss out anything else, i'll be closing this issue for now - but feel free to let me know what you think!
