### ISSUE TITLE
Enable Google sign in with credentials to enable use of One Tap

### ISSUE THREAD

**Issue by noahKind** [supabase/gotrue#341]
Currently Google login is only supported with a pop up provider. If you could pass optionally pass in a credential instead you could enable google one tap https://developers.google.com/identity/gsi/web/guides/overview

**Comment by koba-ninkigumi** [comment]
@kiwicopple @J0 @noahKind

Sign In With Google - One Tap
https://developers.google.com/identity/gsi/web/guides/overview

There is no need to modify the backend goture to make this work.

This issue is actually the same as this issue.
https://github.com/supabase/gotrue-js/issues/169

And there is already a pull request for it.
https://github.com/supabase/gotrue/issues/341

Once this is merged, the Google One-Tap login functionality will be achieved.
(A sample script is also available on this pull request page.)

However, as you can see, we are facing unreasonable requests to create tests, and no progress is being made.

We would appreciate any help from anyone with merge privileges.

**Comment by J0** [comment]
Heya @koba-ninkigumi 

Thanks for the PR and note! Your contribution is important to us and I'm glad to hear that the two issues are actually one. Perhaps we can kill two birds with one PR :) I'm sorry to hear that progress has not been advancing at the rate that you would like. It can be frustrating to wait on a feature to be released when it seems like it's done especially after you have put substantial effort into it.

Don't have context with respect to the PR but I'll take a look at the PR once a slot frees up. I will also table this for discussion during our Auth meeting tomorrow so that we can get back to you ASAP.

If you have immediate concerns, feel free to reach me at @J0 on Discord.

Thanks for your patience!

**Comment by koba-ninkigumi** [comment]
@J0 
Thanks for the reply.
I look forward to the progress of tomorrow's meeting.

**Comment by kangmingtay** [comment]
Seems like the [credential response](https://developers.google.com/identity/gsi/web/reference/js-reference#CredentialResponse) used in [One Tap](https://developers.google.com/identity/gsi/web/guides/overview#google_account_sign-in) doesn't include a nonce value. Unless there is a way for the nonce value to be included in the id token, the current `POST /token?grant_type=id_token` endpoint wouldn't work.

@koba-ninkigumi any ideas?

**Comment by koba-ninkigumi** [comment]
@kangmingtay 

I've been using Google sign-in for a long time.
My PR is exactly what I wrote to solve this problem for myself.

You can find it at https://github.com/supabase/gotrue-js/pull/207

As already mentioned in this PR discussion, Google sign-in supports nonce.

Please refer to the following document.

https://developers.google.com/identity/gsi/web/reference/html-reference#data-nonce
https://developers.google.com/identity/gsi/web/reference/js-reference#nonce

**Comment by hf** [comment]
Since this has been fixed thanks to @koba-ninkigumi in https://github.com/supabase/gotrue-js/pull/207 I'll be closing this issue.
