### ISSUE TITLE
Ability to pass additional URL params to OAuth providers

### ISSUE THREAD

**Issue by lauri865** [supabase/gotrue#357]
# Feature request

Ability to send additional parameters to OAuth providers (e.g. would love to use &hd=domain.tld and &hint=example@domain.tld parameters with Google OAuth. Simple passthrough of parameters would suffice (namespaced or not).

**Comment by kangmingtay** [comment]
Hi @lauri865, have you tried passing query parameters via the redirect url? IIRC this should work `https://project_ref.supabase.co/auth/v1/authorize?provider=google&redirect_to=my_redirect_url.com?query_param=1` 

You will have to add `my_redirect_url.com` to the "Additional Redirect URLs" list but you dont have to include the query params. 

Let me know if this works for you!

**Comment by lauri865** [comment]
That wouldn’t really pass params to the oauth provider, would it? Just the redirect/callback.

**Comment by kangmingtay** [comment]
oh i see what you mean, yeah it wouldn't. Unfortunately, we only allow passing of scopes as query params to the oauth provider for now

**Comment by roseMix** [comment]
@kangmingtay, I really love Supabase and have been testing it for use in my app. However this issue is currently my biggest holdup.

Certain query params are quite a basic need when using specific providers (other than just redirectUri and scopes)

Consider my use case:

I really need the user signing in using Google on Chrome Android to be able to choose from existing logged-in Google accts or add a different one if not exists (even when there is only one acct currently logged in), this is currently only possible when passing a `prompt=select_account` query string (see [here](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#oauth-2.0-endpoints_1) .

Additionally - and this is maybe not as important - Google recommends using the `state` queryParam which is also currently impossible. 

Besides in general, the ergonomics of locking in myriad auth providers with a wide array of different options to just 2 params sounds neat but in reality - to be useful - there needs to be a way to use the auth providers' respective features fully.

**Comment by bnjmnt4n** [comment]
Passing through URL query parameters is possible (and is currently being done for the WorkOS provider). The question is whether GoTrue should always attempt to pass through all query parameters automatically (apart from those that GoTrue uses), or hardcode a list of query parameters for each provider to pass through (which can be more troublesome, but avoids sending invalid requests to the providers).

The `state` query parameter is currently being used by GoTrue itself to store its own state, so it might need a bit of tweaking if client's state should be persisted as well.

**Comment by roseMix** [comment]
> hardcode a list of query parameters for each provider to pass through (which can be more troublesome

I understand you mean because it will need to be constantly validated against the auth providers accepted params. Given that it's currently not possible to use most of the auth providers' to their fullest I believe this is not a significant tradeoff, most providers are quite straightforward about these and mostly they don't get changed very often. Additionally, not all providers need to offer it (at least not immediately).

Maybe a solution would be to add and optional flag to pass through all query params to auth provider (at your own risk of getting rejected by the provider).

**Comment by lauri865** [comment]
Any news? 🙏

**Comment by laznic** [comment]
Also interested in hearing if there are any news regarding this! I'm myself planning to use Discord login, however not being able to pass in `prompt=none` is kind of a turn off (among with other stuff, e.g. no access to provider refresh tokens).

**Comment by ralrom** [comment]
This is also a blocker for me. Specifically, I really need to pass `prompt: select_account` to the Google OAuth provider.

**Comment by liaujianjie** [comment]
> hardcode a list of query parameters for each provider to pass through (which can be more troublesome, but avoids sending invalid requests to the providers)

IMO this would work best since it is cheap to implement. Plus, the community can easily keep the list of parameters up to date since it'll just be an array of strings.

**Comment by hf** [comment]
Please take a look at https://github.com/supabase/gotrue/issues/341 for some similar logic with Google as a provider.

**Comment by kangmingtay** [comment]
hey everyone, this should now be possible since https://github.com/supabase/gotrue/pull/757! thanks for everyone's patience! 

disclaimer: it will be rolled out to all hosted supabase projects over the coming week or so

**Comment by gyulavoros** [comment]
@byyoungjin, were you able to figure this out? I have a similar use case where I'd need to pass along some context identifying the login attempt.

**Comment by C4T4** [comment]
same issue, I get the error: {"code":400,"error_code":"bad_oauth_state","msg":"OAuth callback with invalid state"} with .supabase.co/auth/v1/callback?state=...

**Comment by faniAhmed** [comment]
same issue
{"code":400,"error_code":"bad_oauth_state","msg":"OAuth callback with invalid state"} with .supabase.co/auth/v1/callback?state=...

**Comment by Mantic** [comment]
I also want to be able to pass my own state across OAuth logins.
