### ISSUE TITLE
Apple Login as an OAuth Provider

### ISSUE THREAD

**Issue by infomofo** [supabase/gotrue#37]
# Feature request

## Is your feature request related to a problem? Please describe.

When I go to `auth/settings` I see External Oauth Providers for Google, Github, Gitlab, and Bitbucket. My understanding is that for an ios app, you must also provide Apple as an oauth provider. Is this something you intend to support in Supabase?

## Describe the solution you'd like

I would like to have Apple supported as an external Oauth Provider

## Describe alternatives you've considered

From what I understand, apple's store guidelines require that if you allow another oauth provider you must support apple oauth. If I am building an app powered by supabase I would like to offer google oauth, but I want to make sure this is supported.

**Comment by He1nr1chK** [comment]
Hi, any word on when this might be implemented. Can't use Supabase auth for iOS apps as Apple requires developers to add the "Sign In With Apple" option. Thanks @kiwicopple. Would do it myself but I am completely unfamiliar with GoTrue.

**Comment by Seanmclem** [comment]
@kiwicopple Hi, the seriousness of Supabase as a platform in this space is called into question by the apparent low priority of this issue. This requirement by Apple has been in place for over a year. The 3rd party authentication should be considered broken without it. It is my opinion that this should be a bug not a feature request. Tried to open one [here](https://github.com/supabase/supabase/issues/1391) but I guess it's a duplicate. 

I know I could try and contribute since it's open source but I have little time. That's why I'm looking to use something like Supabase rather than doing everything it does from scratch. However, it almost sounds like the goal of Supabase is to one day be a thriving business with commercial pricing options. But it's difficult to imagine that is a serious pursuit with such a glaring hole left unattended for so long.

**Comment by kiwicopple** [comment]
Hey @Seanmclem, thanks for bumping this issue.  We know this is an important task - we are even [hiring people](https://twitter.com/supabase_io/status/1389078045449854978) to help with it. Our team is stretched extremely thin right now. 

As a small note, the community functions a lot better when it's collaborative rather than accusatory. I understand if you have no time to contribute so a good way to help is to push other developers here who have the time/skills to help solve it. That way, everyone wins. If you know a good Go developer who can solve this - please let them know that we will send them swag if they can submit a PR.

**Comment by Seanmclem** [comment]
> Hey @Seanmclem, thanks for bumping this issue.  We know this is an important task - we are even [hiring people](https://twitter.com/supabase_io/status/1389078045449854978) to help with it. Our team is stretched extremely thin right now. 
> 
> As a small note, the community functions a lot better when it's collaborative rather than accusatory. I understand if you have no time to contribute so a good way to help is to push other developers here who have the time/skills to help solve it. That way, everyone wins. If you know a good Go developer who can solve this - please let them know that we will send them swag if they can submit a PR.

Thanks, yes I've applied. I had no intention to make accusations. Rather to push the importance of the issue to developers.

**Comment by awalias** [comment]
looks like this is what we want: https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

just having trouble finding the client_id and client_secret, going to keep digging

**Comment by He1nr1chK** [comment]
Hi @awalias, looks good. I also found this repo that has already implemented sign in with apple written in GO: https://github.com/Timothylock/go-signin-with-apple

**Comment by He1nr1chK** [comment]
Hi @kiwicopple @awalias, any update on this? I see that Twitter was just added as a OAuth provider. Can't use any third party providers on iOS if we don't provide sign in with Apple as an option

**Comment by kangmingtay** [comment]
Hey @He1nr1chK, we'll be working on this next! Stay tuned!

**Comment by Seanmclem** [comment]
Might difficult to use in an App without the ability to use with Expo Auth Session or something similar. Any idea if that will work?

**Comment by Seanmclem** [comment]
> Hey @Seanmclem, I'm not too familiar with Expo Auth Session but I'll do up a v1 and we can see how to improve it from there! 

Thanks. I guess I was just saying without a functional app implementation for supabase-auth, the Apple sign in would be less useful.

**Comment by He1nr1chK** [comment]
Hi @kangmingtay, thanks for all the great work. I just saw your PR for apple authentication. The problem that I think @Seanmclem is referring to is the fact that there is no practical way for us to use the implemented apple auth provider (or any third party provider for that matter) in React Native (or Flutter I assume). The issue, as touched on in [this](https://github.com/supabase/supabase-js/issues/145#issuecomment-813106568) thread, is that the redirects do nothing when calling `supabase.auth.signIn()`. The call just returns null for both session and user. From what I have gathered, the crux of the problem lies in RN (or Expo in my case) not having a way of handling the redirect as it is currently implemented. The solution suggested in the above mentioned thread is to expose a function for all third party providers to sign in by passing an access_token to the Supabase `signIn()` method and then getting the user's data back. This is the way that Firebase handles the sign in for Expo. What are your thoughts on this?

**Comment by awalias** [comment]
If I understand the linked thread correctly then we should be able to call [/callback](https://github.com/supabase/gotrue#get-callback) directly with the relevant `access_token` etc.

we also added the ability to redirect to deep mobile links using "Additional Redirect URLs", I believe it's being used on flutter already: https://github.com/supabase/supabase-dart/issues/20

closing this now as I don't think there's any additional backend work required?

**Comment by davidmartos96** [comment]
@awalias 
> If I understand the linked thread correctly then we should be able to call /callback directly with the relevant access_token etc.

Is there any issue that tracks this? It is a very useful features for mobile applications where a native Google / Apple sign in  dialog can be shown to the users. Those dialogs already obtain a valid access_token that could be sent to the backend.
