### ISSUE TITLE
"Email not confirmed" error even though "Enable email confirmations" is disabled

### ISSUE THREAD

**Issue by jnorris441** [supabase/gotrue#413]
# Bug report

## Describe the bug

I am getting the error "Email not confirmed" when trying to sign in, even though the setting "Enable email confirmations" is disabled in the admin.

If the admin flag is not intended to disable the confirmation gating and merely disables sending the emails, it should be described a little better to prevent confusion.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable "Enable Email Signup" and disable "Enable email confirmations" in the admin
2. create an account via supabase.auth.api.createUser() with an email and password
3. attempt to login via supabase.auth.signIn()
4. error "Email not confirmed"

## Expected behavior

Should be able to sign in without confirming if the confirmation setting is off

## Workaround

Send `email_confirm: true` into supabase.auth.api.createUser() to confirm the user

**Comment by kangmingtay** [comment]
hey @jnorris441, `supabase.auth.api.createUser()` actually calls the `/admin` api endpoint in gotrue. Since it's the admin user who usually calls these endpoints, they should have the ability to overwrite the admin configuration set on the dashboard. 

Also, as you mentioned, `api.createUser()` now supports taking in [`AdminUserAttributes`](https://github.com/supabase/gotrue-js/blob/c272277d0572b53ff3ae277fcb7b8e095b6d1134/src/lib/types.ts#L142-L149) which allows you to specify whether you want `email_confirm` or `phone_confirm`. 

Yeah we should describe this better on the docs, but thanks for raising this up!

**Comment by kiwicopple** [comment]
fixed by https://github.com/supabase/supabase/pull/6010
