### ISSUE TITLE
Send confirm signup and change email address emails when user is created or updated through the bankend

### ISSUE THREAD

**Issue by pico-project** [supabase/gotrue#438]
# Feature request

## Describe the solution you'd like

Add ability to send user confirm signup and change email address emails when user is created with supabase.auth.api.createUser and user data is updated with supabase.auth.api.updateUserById

**Comment by hf** [comment]
Hey this is somewhat out of scope, as the admin API is intended to be as flexible as possible. Different projects will have different requirements. Some may want to send an email, others not. Thus, it is unlikely we'll add support for this in GoTrue. 

Since the admin APIs are intended to be used in a server environment which you fully trust, it is trivial to add email sending functionality when you need it.
