### ISSUE TITLE
`samesite` option to set it to `none` to allow cross domain server to read cookies during oAuth call back

### ISSUE THREAD

**Issue by bhvngt** [supabase/gotrue#512]
# Bug report

## Describe the bug

Currently, after the oAuth callback [setCookie](https://github.com/supabase/gotrue/blob/c9f1ed5731b102a40bae113e972c0e7674a9195b/api/token.go#L600) code leaves `sameSite` option blank. As per the recent browser [changes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax), `lax` has replaced `none` as the default value for `sameSite` option when it is blank.

Without `sameSite` set to `none`, server is not able to read the cookies sent during the callback. Hence, an additional client-side call is required to sent the `access-token` to the server to allow for server-side calls `authenticated` user.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

During a typical oAuth call, following cookie is sent to the browser

![image](https://user-images.githubusercontent.com/79074469/175759888-50a5772f-d2d7-469b-b123-b036e23987f0.png)

## Expected behavior

`gotrue` should allow an option to set `sameSite` cookie option for `oAuth` callbacks. 

With this change, cross domain server should be able to read cookies during the callback. This will save an extra trip from client side to send the access token to the server. 

As a side-effect it also leads to a much better dev experience to protect private pages on the client-side. Currently, client-side can ascertain oAuth `success` only after the page is loaded. 

## System information

- Browser (if applies) chrome
- Version of supabase-js: latest

**Comment by hf** [comment]
We are not planning on supporting the `SameSite=none` cookie option for cookies issued by Supabase Auth. This is because those cookies are for internal Supabase Auth / GoTrue use and are not meant to be used by third parties. There are no guarantees that those cookies represent a valid user session (though they likely do). We also can't guarantee backward and future compatibility of those cookies.

We do suggest using only the concept of access and refresh token to identify a user's session on a particular web browser. Your single-page app does not have to fire a request to transfer cookies on the origin it runs on. Here's a snippet you can use to set cookies for a server-side application running on the domain your application is running on:

```typescript
supabase.auth.onAuthStateChange((event, session) => {
  if (event === "SIGNED_OUT" || event === "USER_DELETED") {
    // delete cookies on sign out
    const expires = new Date(0).toUTCString();
    document.cookie = `my-access-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
  } else if (event === "SIGNED_IN" || event === "TOKEN_REFRESHED") {
    const maxAge = 100 * 365 * 24 * 60 * 60; // 100 years, never expires
    document.cookie = `my-access-token=${session.access_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=${session.refresh_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
  }
})
```

Here you can customize the cookies for your application as you wish.

**Comment by tomelliot** [comment]
@hf do you have a recommendation for authorizing an SPA that is run on a 3rd party's domain? The use case is as an extension/plugin for a 3rd party application.

My naive attempt to embed an iframe with my domain and then pass the session across with `window.parent.postMessage` works in Firefox but not Chrome due to the cookie SameSite restrictions.
