### ISSUE TITLE
Keycloak Login results in Error: "Unable to exchange external code"

### ISSUE THREAD

**Issue by valerius21** [supabase/gotrue#516]
# Bug report

## Describe the bug

After setting up an instance of Keycloak and using current examples with their latest versions, logging in via. the thrid-party-service Keycloak on a local instance results in an error, which message is "Unable to exchange external code", found in the redirect URL.

## To Reproduce

1. Follow the documentation on setting up Keycloak for Supabase, https://supabase.com/docs/guides/auth/auth-keycloak.
2. Initialize a new project with `npx create-next-app --example "https://github.com/valerius21/auth-helpers/tree/main/examples/nextjs"`
    1. Enter the corresponding credentials in a `.env.local` file (`NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY`)
    2. Change `pages/index.tsx:38` from `providers={["google", "github"]}` to `providers={["google", "github", "keycloak"]}`
    3. Start the Dev Server with `yarn dev`
    4. (This Step is also reproducible with the official supabase-js client)
3. The site at `http://localhost:3000` should have three buttons, one of which has no icon inside.  ![image](https://user-images.githubusercontent.com/10323945/174764138-a96add9d-f017-423d-9b7c-9f9227290171.png)
5. Click the button and login on to the local Keycloak instance
6. Redirected back to the authentication form, no session is established and an error code in the URL is present.
```
http://localhost:3000/?error=server_error&error_description=Unable+to+exchange+external+code%3A+392cabd5-b422-446a-8497-e4f184453157.0887172c-5c95-44a4-944b-d975911a9563.46e8656a-f404-41c8-ab90-baa7ffb0d727
```

## Expected behavior

A user session, similar to other OAuth2 providers, like Google, GitHub, etc., where querying DB content and one's user profile is possible.

## Screenshots

https://user-images.githubusercontent.com/10323945/174766209-12eec916-b964-402a-b6ec-bf1da962c164.mp4

## System information

- OS: Ubuntu Linux
- Browser: Chrome, Brave
- Version of supabase-js: latest
- Version of Node.js: 16.15.x

## Previous attempts to resolve the issue
- Checking the Keycloak credentials of whitespaces
- Adding SSL did not resolve the issue
- Inspecting the supabase instance logs of errors, but only, as intended, finding `302` requests.
- Using the supabase client in other frameworks and in other contexts to attempt an authentication request.

**Comment by koakh** [comment]
Hello
I have the same problem using [app.supabase.com](app.supabase.com)

redirect url with failure **"Unable to exchange external code"**

```
http://localhost:3000/?error=server_error&error_description=Unable+to+exchange+external+code%3A+a95bcaef-bb46-4c04-9ec6-2a81877a68f0.be71884e-2598-4dea-9d0f-61766b30e403.dfae8b4b-e82d-466c-ac57-d112d9b92d7c
```

another unrelated strange thing is
when I use a **self hosted supabase** using this guide [Self Hosting With Docker](https://supabase.com/docs/guides/hosting/docker)
**I don't see the auth providers**, its like a **incomplete supabase**, without many functions, like oauth2 auth providers
we can see it in bellow image

![image](https://user-images.githubusercontent.com/6191096/177656043-4a17566b-a14b-4abf-a381-c432d77014ac.png)

How can I use self hosted supabase with oauth2 providers to test it with keycloak, like @valerius21

**Comment by valerius21** [comment]
@koakh When starting a local instance, add the following lines to your [here](https://github.com/supabase/supabase/blob/b749be5c1eacb4ad80b6d7fb334ea16a123720b4/docker/docker-compose.yml#L78) `docker-compose.yml` 

```
      GOTRUE_EXTERNAL_KEYCLOAK_ENABLED: "true"
      GOTRUE_EXTERNAL_KEYCLOAK_CLIENT_ID: "<client id>"
      GOTRUE_EXTERNAL_KEYCLOAK_SECRET: "<client secret>"
      GOTRUE_EXTERNAL_KEYCLOAK_REDIRECT_URI: "http://localhost:<PORT of your webapp>/"
      GOTRUE_EXTERNAL_KEYCLOAK_URL: "http://<keycloak instance>/auth/realms/<realm>"
```

**Comment by koakh** [comment]
I will try it later (asap) and update my reply with feedback, maybe will be useful for others

thanks @valerius21

**Comment by valerius21** [comment]
@koakh, thank you very much for your write-up! I'll try to replicate everything once I find time to do it. IMO the documentation needs some updating before someone gets into the rabbit hole of trying to find out how it works.

**Comment by hf** [comment]
Thank you @koakh for the write up. I'll try to summarize it for others.

When running both Keycloak and GoTrue locally, you need to make sure that both of them can actually talk to each other over the operating system's network layer. There is no one way to fix the problem, depending on how you have set up the Keycloak or GoTrue instance to run.

Note that typically things running within a docker container can't talk to things running outside of it, especially on localhost. I believe this to be the cause of the errors with the form of:

```
Post \"http://localhost:8080/auth/realms/SupaBase/protocol/openid-connect/token\": dial tcp 127.0.0.1:8080: connect: connection refused
```

It may be just easier to host Keycloak on a public web server with a correct URL to avoid dealing with complex docker networking issues especially if you don't have sufficient knowledge or experience in dealing with them.

**Comment by olee** [comment]
@koakh Hey, I'm having the same issue with auth not being able to reach keycloak because it is running in another container.
How did you solve this issue in the end then? When I set `GOTRUE_EXTERNAL_KEYCLOAK_URL: http://keycloak:8085/realms/app` the redirect to keycloak in the browser just gets broken.

**Comment by koakh** [comment]
Hello @olee 

Sorry for late answear, 
Currently I'm not at home, and I don't remember the solution from my memory right now
Let me see it in my project, and I update here asap

but I think you need to use a public domain in GOTRUE_EXTERNAL_KEYCLOAK_URL like http://mydomain.com:8085/realms/app, this is because auth flow in browser must reach it, but I can be wrong, because I do it more than a year now, 
and like I said I don't remeber (be sure)

try and if i'm wrong I will check it in my project

**Comment by olee** [comment]
I already found a quite simlar solution based on what you had and added it to my comment above.
For me it was slightly different, because I was executing the whole thing on windows.

Thanks anyways and also for all the investigation you did above which helped me find the solution 👍

**Comment by huseyingulec** [comment]
Hello guys, I came across the same issue on production.

I have a coolify setup where i am hosting keycloak and supabase. They both have their own domain like `keycloak.mydomain.com` and `supabase.mydomain.com`. I am having `request_timeout` error after login since my supabase container cannot access `keycloak.mydomain.com`. 

I tried to use a custom network and I was able to access keycloak from supabase via its container name but i couldn't find any solution to access via its domain.

container name access: `"http://<container-name>:8080/auth/realms/SupaBase"`

please let me know if you know anything. Thanks in advance for all
