### ISSUE TITLE
Auth: Update email account will not update the adress to log in

### ISSUE THREAD

**Issue by Etheonor** [supabase/gotrue#67]
If you update the email adress with supabase.auth.update, it will not replace the old one but create a "new_email" element in your auth.user object. 

Therefore, when you try to log in again with the new updated email, it will not work and you'll have to use the old one.

**Comment by kiwicopple** [comment]
OK I did some testing here and can confirm: https://github.com/supabase/gotrue-js/issues/57

We need to decide whether to handle this in the client or the server.

We could handle it in the client like this: https://github.com/supabase/gotrue-js/pull/58. I'm not sure why Netlify chose this strategy to start with

**Comment by Etheonor** [comment]
Another thing with this one, the "new_email" entry is not in the user object when you use Auth.useUser(), so there is no way to check if the user has entered a new email or not. 

For the moment this problem is completely blocking me from putting my authentication feature online.

**Comment by Etheonor** [comment]
Another thing, when we update this new_email element, if you do a supabase.auth.user() right after, you will not have the updated user. You have to logout/login to have the new_mail properly updated. 

This is far from ideal

**Comment by icecream78** [comment]
@kiwicopple @awalias I've looked though code that implements user change. That code is responsible for email change too, but I am not sure that it has been worked ever. Logic that handles email change placed in handler that requires auth token and has PUT method, not GET. Plus, default variable MAILER_URLPATHS_EMAIL_CHANGE is / and GOTRUE doesn't have handler for that url at all=) 
My preposition for fixing that problem is next. In verify handler add new one type - email_change and write corresponding logic for handling changed email. 
Or it isn't necessary changes? What do you think about that?

**Comment by awalias** [comment]
related: https://github.com/supabase/gotrue/issues/60

**Comment by kangmingtay** [comment]
Hey @Etheonor, i think this issue has been resolved already. You can update your email with `supabase.auth.updateUser` which will return a user object with the `new_email` field. You'll have to verify the email change confirmation link that's sent to your email before you can login with the `new_email`.

**Comment by alexcsloan** [comment]
I'm having this exact same issue. I call `supabase.auth.updateUser` with the new email. I then verify the new email address successfully. I have confirmed that the user now has `new_email` set and `email_change_confirm_status` is set to 1. This makes it seem like the new email should be set up properly. However, I am unable to login with the new email address.
