### ISSUE TITLE
signUp() user data is not obfuscated/fake when returned

### ISSUE THREAD

**Issue by samuel-stubbs** [supabase/gotrue#748]
# Bug report

## Describe the bug
When using the create a new user function signUp(), when an existing user is queried it returns a user object with valid information that is not obfuscated/fake as the documents suggest. Only once the user has confirmed their email is the id obfuscated but information such as phone, email and user metadata is still valid.

https://github.com/supabase/gotrue/blob/85cff37bac7fdd22a87235890caca7d6ace6c244/api/signup.go#L257

Why are we only removing one or the other when it comes to the provider phone & email fields, should they not both be removed if obfuscating?
https://github.com/supabase/gotrue/blob/85cff37bac7fdd22a87235890caca7d6ace6c244/api/signup.go#L267

// Should be used whenever we want to prevent information about whether a user is registered or not from leaking
func sanitizeUser()

Why does the user need to be sanitized for "confirm email" when enabled but not when "confirm email" is disabled? should it not simply return "User already registered"? one seems to be leaking if a user is registered does it not?

**Comment by kangmingtay** [comment]
Hey @samuel-stubbs, for more context, we initially decided not to obfuscate the data when "confirm email" is disabled because that action is already inherently insecure. When "confirm email" is disabled, it returns an access token and refresh token pair on signup and there is no way to "fake" that data. An attacker can easily use the access token to determine if the user actually exists or not.

When we move to v2, we intend to do away with obfuscation completely since obfuscation makes the DX of the API confusing. If a developer wants the data returned from gotrue to be obfuscated and not leak information, they should handle the obfuscation via a proxy server. This would also allow for more customization on the developer's end as to how granular they want to obfuscate the data.

We'll be closing this issue for now but thanks for raising it up!
