### ISSUE TITLE
When a user email address is updated, a new account is created to same provider

### ISSUE THREAD

**Issue by vmiguellima** [supabase/gotrue#85]
# Chore

A registered user via Github Auth, updates the email address.

## Describe the chore

A registered and authenticated user via Github Auth updates its email address. And the change is made with success.

Then when it logouts. And sign in again via Github. It is created a new user.

The database has now two users from the same provider.

## Additional context

Steps to reproduce:

1. I'm using `vercel/nextjs-subscription-payments` as starting point.
2. Connect it to Supabase.io
3. Sign in with Github, Then we make a update email request using:
```js
try {
    const updates = {
        email: email
    }
    const { error, data } = await auth.api.updateUser(session.access_token, updates);

    if (error) {
        throw error
    }
} catch (error) {
    alert(error.message)
}
```
4. Then **supabase.io** sends a email change confirmation to the new user email address
   1. we use the provided token, and send an email update request:
```js
try {
  const updates = {
    email: email,
    email_change_token: changeEmailToken
  }
  const { error, data } = await auth.api.updateUser(session.access_token, updates);

  if (error) {
    throw error
  }
}
```
5. **supabase.io** responds with a success (200) and the email is successfully updated
6. Logout the user
7. Sign in again with Github
8. A new account is created

**Comment by kangmingtay** [comment]
Took a look at the [/PUT user endpoint](https://github.com/supabase/gotrue/blob/1f83884c1e45f79bb9ff30c7c7566af293c7267b/api/user.go#L52) recently and had some thoughts on this issue:

Constraints
1. If the user initially signs up via Github, the user should still be able to sign into the same account via Github _even_ if the user changes his/her email.
2. Since gotrue treats email as identity, changing the email would remove the association between Github and the app account created, which results in a subsequent sign-in with Github creating a new account. 
3. From my POV, a user would only want to change the email address if they want the app notifications to be sent to a _different email address_.

Solution 1: We do not allow users to update their email if they chose to sign up via an external oauth provider like Github.

Solution 2: We can create a key in the UserMetaData column called "primary_email" for all users which will be the same as the email address they used to sign up. If a user who signed up via an external provider tries to update their email, the "primary_email" in UserMetaData will be updated instead of the Email field used as identity.

**Comment by bariqhibat** [comment]
Hey @kangmingtay, can I work on this for my first contribution?

**Comment by J0** [comment]
Hey @bariqhibat,

Sorry for the delayed reply on this. Feel free to take up the issue if you're still interested.

Thanks!
Joel

**Comment by bariqhibat** [comment]
Hi @J0,

Has this not been resolved yet? If so then I can start looking into it, bear with me since it's been a while since I've taken a look into the repo. Can assign me on this! Thanks!

**Comment by kangmingtay** [comment]
@bariqhibat correct me if im wrong but i think this issue has been fixed already, we don't really treat email as identity for oauth logins, we use the oauth provider id returned instead. This means that even if you update your email on github, the oauth provider id doesn't change so a new user wouldn't be created.

**Comment by J0** [comment]
Hey @kangmingtay ,

Sounds good, shall we go ahead and close the issue?

Hey @bariqhibat,

Seens like I'm not quite up to date on this issue 😅  Feel free to let us know if the issue still persists for you or if there are any other issues that you'd like to take up.

Thanks!
