### ISSUE TITLE
Custom user id generation (e.g. ulid or entity type prefix)

### ISSUE THREAD

**Issue by tonyxiao** [supabase/gotrue#888]
# Feature request

We have a convention of prefixing ids based on the type of entity (see Stripe API) and would like to thus generate our user ids with `usr_` such that they look like `usr_xxxxxx`. Further more we prefer `ulid` rather than `uuid`, which is not only more compact (when represented as string, not binary) but also contains a timestamp. 

Thus we'd love a way to customize how user id is generated. Perhaps with postgres function that gotrue calls out to generate ids? It can still be of `uuid` type as I'm sure updating database schema from `uuid` to `varchar` can be tricky. However even the ability to generate `ulid` style `uuid` (see https://www.ulidtools.com/) is already a huge boon, then we can always add a view / generated column to prefix the `usr_` that we want in our application

**Comment by GaryAustin1** [comment]
I believe you will need to request a gotrue change for this.  Gotrue does not use the database to generate the UUID, but does it in Go code...  https://github.com/supabase/gotrue/blob/a4a96c0bf5e09b80fbe345e678a859f07948b9d1/models/user.go#L70

**Comment by tonyxiao** [comment]
https://github.com/supabase/gotrue#post-put-adminusersuser_id what about this one? It seems that there should be some ability to provide an id when creating user 
![CleanShot 2023-01-10 at 21 38 20@2x](https://user-images.githubusercontent.com/696842/211657193-d6907f4c-8426-4ce3-8497-20af4f2eb341.png)

**Comment by GaryAustin1** [comment]
The ultimate authority will be a Supabase dev,
But I believe the way that call works is if you provide a UUID then it will UPDATE that user if it finds it, otherwise error.
If you don't provide a UUID then it will create a new user with a UUID gotrue generates.

That is how the javascript code calls it.

**Comment by tonyxiao** [comment]
How do I invoke the right call (with custom uuid) when using supabase-js auth? Don't see a corresponding call whether in the client or admin sdk

**Comment by hf** [comment]
Hey @tonyxiao,

It's unlikely we'll be supporting this as it creates quite a bit of complexity. We use v4 UUIDs exclusively both because they can be generated in the database fairly quickly. We also will not be supporting UUIDs generated from the outside as this can lead to some interesting security problems.

It may be the case that we do add some form of object tagging or developer metadata (similar to how Stripe and AWS do it) to help you identify objects easily. We don't have a timeline on this, though I suspect with our current SSO effort this may start appearing in some aspects.

I'll close this issue for now.

**Comment by tonyxiao** [comment]
@hf the uuids are not generated in database, they are generated directly in go though.

```
// NewUser initializes a new user from an email, password and user data.
func NewUser(phone, email, password, aud string, userData map[string]interface{}) (*User, error) {
	id, err := uuid.NewV4()
```

What are the security issue you see for an externally generated uuid? Given that this is the admin endpoint, not the client side endpoint where user signs up.
