### ISSUE TITLE
Create user with login instead of email

### ISSUE THREAD

**Issue by szmarczak** [supabase/gotrue#903]
# Feature request

## Is your feature request related to a problem? Please describe.

Email shouldn't be a requirement. I'm building a website where email is optional.

## Describe the solution you'd like

```js
const { data, error } = await supabase.auth.signUp({
  login: 'example',
  password: 'example-password',
})

const { data, error } = await supabase.auth.signIn({
  login: 'example',
  password: 'example-password',
})
```

## Describe alternatives you've considered

None yet.

**Comment by kangmingtay** [comment]
Hey @szmarczak, we don't plan on adding username-password sign ups as a login mechanism for gotrue. However, anonymous sign-ins (#68) is on the roadmap and that might help with your use case in the future. 

Closing this issue out since we won't be implementing this but feel free to reopen it or clarify if I've missed something.

**Comment by OrganizedAdviser** [comment]
While not common, I do wish this was available. I am building an app for students to use and capturing email is personally identifying information, so I’d strongly prefer to not collect it, as it’s a huge barrier to adoption with student privacy regulations. The solution I have is that their teacher (who must have an email-based account), can manually reset their passwords.
