### ISSUE TITLE
Revise counter-intuitive invite link design

### ISSUE THREAD

**Issue by gaodeng** [supabase/gotrue#908]
The current design of invite links for Supabase immediately invalidates the link after first opening, which is counter-intuitive and confusing for users. It would improve the user experience to have a more intuitive design, such as allowing for multiple uses or providing an option to resend the invite link or having a time-limited design, such as expiring after one week.

**Comment by gaodeng** [comment]
@kiwicopple 
I understand that the one-time use of the invitation link is a security feature, but it can also cause confusion for users. In normal system design, the invitation link should not pose any security risks. I suggest re-evaluating the design to find a balance between security and user experience. Instead of limiting the use of the invitation link to one time only, other measures  can be implemented to ensure security without causing confusion for users.

**Comment by kangmingtay** [comment]
Hi @gaodeng, it would be great if you can share your usecase on why you require your users to click on the invite link more than once? We strive to design an API that's both secure by default and user-friendly and like most software systems design, it always requires a tradeoff. I believe a possible solution here would be to show to the user a clearer error message so that they know that the invite link has been used already or if they need to request for another one.

**Comment by gaodeng** [comment]
Hi @kangmingtay 
The restriction on only being able to click the invite link once does not align with user expectations, as most other systems do not have such a limitation.
